### ISSUE TITLE
Arabic issue

### ISSUE THREAD

**Issue by abbasyusuf** [erfan4lx/TelegramChannelMemberAdder#1]
Hi, 

It's very good bot but unfortunately it's not working with the Arabic language, I tired to fetch one of groups which is all names are written in Arabic but it didn't work. 

```

Enter a number (or press ENTER to skip): 11

[+] Fetching Members...
Traceback (most recent call last):
  File "erfan4lx.py", line 218, in <module>
    client.loop.run_until_complete(main())
  File "C:\Pythone36\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "erfan4lx.py", line 180, in main
    all_participants = await client.get_participants(target_group)
  File "C:\Pythone36\lib\site-packages\telethon\client\chats.py", line 466, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Pythone36\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Pythone36\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Pythone36\lib\site-packages\telethon\client\chats.py", line 200, in _load_next_chunk
    results = await self.client(self.requests)
  File "C:\Pythone36\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Pythone36\lib\site-packages\telethon\client\users.py", line 73, in _call
    raise MultiError(exceptions, results, requests)
  File "C:\Pythone36\lib\site-packages\telethon\client\users.py", line 62, in _call
    result = await f
telethon.errors.rpcerrorlist.ChatAdminRequiredError: Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)

```

**Comment by erfan4lx** [comment]
Hello my friend, This error you got not because that channel are Arabic! Because your account don't have admin access to add members. Be sure you have admin access for add member in channel.

Good luck

**Comment by abbasyusuf** [comment]
Thank you erfan4lx  for your response. I wasn't trying to add members, I tried to read and fetch the members details so then the script will create the members sheet for me, so I can use this sheet to add the members to a new channel. Is there anyway to do that? I mean it's like taking the members from another channel which is not yours and add them to your channel.

**Comment by erfan4lx** [comment]
You're welcome. No it's not possible

**Comment by abbasyusuf** [comment]
Thank you erfan4lx
